version: "3.4"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qa-api
      - qa-ui
    ports:
      - 7800:7800

  qa-api:
    build:
      context: ./qa-api
      dockerfile: Dockerfile.prod
    image: qa-api
    expose:
      - 7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env
    deploy:
      restart_policy:
        condition: on-failure

  qa-ui:
    build:
      context: ./qa-ui
      dockerfile: Dockerfile.prod
    image: qa-ui
    expose:
      - 3000
    depends_on:
      - qa-api
    deploy:
      restart_policy:
        condition: on-failure

  llm-api:
    build:
      context: ./llm-api
      dockerfile: Dockerfile.prod
    image: llm-api
    expose:
      - 7000
    deploy:
      restart_policy:
        condition: on-failure

  database:
    container_name: database-server-dab-p2-bf006f69-136b-4835-8bca-f55abd81c2fa
    image: postgres:14.1
    env_file:
      - project.env
    deploy:
      restart_policy:
        condition: on-failure

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    deploy:
      restart_policy:
        condition: on-failure

  e2e-playwright:
    entrypoint: "/bin/true"
    build:
      context: ./e2e-playwright
      dockerfile: Dockerfile.prod
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
    deploy:
      restart_policy:
        condition: on-failure
